export type CountryCallingCode = {
  name: string;
  iso2: string;
  dialCode: string;
};

export const COUNTRY_CALLING_CODES: CountryCallingCode[] = [
  { name: "Ghana", iso2: "GH", dialCode: "+233" },
  { name: "Afghanistan", iso2: "AF", dialCode: "+93" },
  { name: "Albania", iso2: "AL", dialCode: "+355" },
  { name: "Algeria", iso2: "DZ", dialCode: "+213" },
  { name: "Argentina", iso2: "AR", dialCode: "+54" },
  { name: "Australia", iso2: "AU", dialCode: "+61" },
  { name: "Austria", iso2: "AT", dialCode: "+43" },
  { name: "Bangladesh", iso2: "BD", dialCode: "+880" },
  { name: "Belgium", iso2: "BE", dialCode: "+32" },
  { name: "Benin", iso2: "BJ", dialCode: "+229" },
  { name: "Brazil", iso2: "BR", dialCode: "+55" },
  { name: "Burkina Faso", iso2: "BF", dialCode: "+226" },
  { name: "Cameroon", iso2: "CM", dialCode: "+237" },
  { name: "Canada", iso2: "CA", dialCode: "+1" },
  { name: "Chile", iso2: "CL", dialCode: "+56" },
  { name: "China", iso2: "CN", dialCode: "+86" },
  { name: "Colombia", iso2: "CO", dialCode: "+57" },
  { name: "Congo (DRC)", iso2: "CD", dialCode: "+243" },
  { name: "Cote d'Ivoire", iso2: "CI", dialCode: "+225" },
  { name: "Cuba", iso2: "CU", dialCode: "+53" },
  { name: "Czech Republic", iso2: "CZ", dialCode: "+420" },
  { name: "Denmark", iso2: "DK", dialCode: "+45" },
  { name: "Egypt", iso2: "EG", dialCode: "+20" },
  { name: "Ethiopia", iso2: "ET", dialCode: "+251" },
  { name: "Finland", iso2: "FI", dialCode: "+358" },
  { name: "France", iso2: "FR", dialCode: "+33" },
  { name: "Gabon", iso2: "GA", dialCode: "+241" },
  { name: "Gambia", iso2: "GM", dialCode: "+220" },
  { name: "Germany", iso2: "DE", dialCode: "+49" },
  { name: "Greece", iso2: "GR", dialCode: "+30" },
  { name: "Guinea", iso2: "GN", dialCode: "+224" },
  { name: "Hungary", iso2: "HU", dialCode: "+36" },
  { name: "India", iso2: "IN", dialCode: "+91" },
  { name: "Indonesia", iso2: "ID", dialCode: "+62" },
  { name: "Iran", iso2: "IR", dialCode: "+98" },
  { name: "Iraq", iso2: "IQ", dialCode: "+964" },
  { name: "Ireland", iso2: "IE", dialCode: "+353" },
  { name: "Israel", iso2: "IL", dialCode: "+972" },
  { name: "Italy", iso2: "IT", dialCode: "+39" },
  { name: "Japan", iso2: "JP", dialCode: "+81" },
  { name: "Jordan", iso2: "JO", dialCode: "+962" },
  { name: "Kenya", iso2: "KE", dialCode: "+254" },
  { name: "Kuwait", iso2: "KW", dialCode: "+965" },
  { name: "Lebanon", iso2: "LB", dialCode: "+961" },
  { name: "Liberia", iso2: "LR", dialCode: "+231" },
  { name: "Libya", iso2: "LY", dialCode: "+218" },
  { name: "Malaysia", iso2: "MY", dialCode: "+60" },
  { name: "Mali", iso2: "ML", dialCode: "+223" },
  { name: "Mexico", iso2: "MX", dialCode: "+52" },
  { name: "Morocco", iso2: "MA", dialCode: "+212" },
  { name: "Netherlands", iso2: "NL", dialCode: "+31" },
  { name: "New Zealand", iso2: "NZ", dialCode: "+64" },
  { name: "Niger", iso2: "NE", dialCode: "+227" },
  { name: "Nigeria", iso2: "NG", dialCode: "+234" },
  { name: "Norway", iso2: "NO", dialCode: "+47" },
  { name: "Pakistan", iso2: "PK", dialCode: "+92" },
  { name: "Philippines", iso2: "PH", dialCode: "+63" },
  { name: "Poland", iso2: "PL", dialCode: "+48" },
  { name: "Portugal", iso2: "PT", dialCode: "+351" },
  { name: "Qatar", iso2: "QA", dialCode: "+974" },
  { name: "Romania", iso2: "RO", dialCode: "+40" },
  { name: "Russia", iso2: "RU", dialCode: "+7" },
  { name: "Saudi Arabia", iso2: "SA", dialCode: "+966" },
  { name: "Senegal", iso2: "SN", dialCode: "+221" },
  { name: "Sierra Leone", iso2: "SL", dialCode: "+232" },
  { name: "Singapore", iso2: "SG", dialCode: "+65" },
  { name: "South Africa", iso2: "ZA", dialCode: "+27" },
  { name: "South Korea", iso2: "KR", dialCode: "+82" },
  { name: "Spain", iso2: "ES", dialCode: "+34" },
  { name: "Sri Lanka", iso2: "LK", dialCode: "+94" },
  { name: "Sudan", iso2: "SD", dialCode: "+249" },
  { name: "Sweden", iso2: "SE", dialCode: "+46" },
  { name: "Switzerland", iso2: "CH", dialCode: "+41" },
  { name: "Syria", iso2: "SY", dialCode: "+963" },
  { name: "Tanzania", iso2: "TZ", dialCode: "+255" },
  { name: "Thailand", iso2: "TH", dialCode: "+66" },
  { name: "Togo", iso2: "TG", dialCode: "+228" },
  { name: "Tunisia", iso2: "TN", dialCode: "+216" },
  { name: "Turkey", iso2: "TR", dialCode: "+90" },
  { name: "Uganda", iso2: "UG", dialCode: "+256" },
  { name: "Ukraine", iso2: "UA", dialCode: "+380" },
  { name: "United Arab Emirates", iso2: "AE", dialCode: "+971" },
  { name: "United Kingdom", iso2: "GB", dialCode: "+44" },
  { name: "United States", iso2: "US", dialCode: "+1" },
  { name: "Vietnam", iso2: "VN", dialCode: "+84" },
  { name: "Zambia", iso2: "ZM", dialCode: "+260" },
  { name: "Zimbabwe", iso2: "ZW", dialCode: "+263" },
];
